// Code generated by reactGen. DO NOT EDIT.

package testutils

import "github.com/lijianying10/react"

type WrapperElem struct {
	react.Element
}

func buildWrapper(cd react.ComponentDef) react.Component {
	return WrapperDef{ComponentDef: cd}
}

func buildWrapperElem(children ...react.Element) *WrapperElem {
	return &WrapperElem{
		Element: react.CreateElement(buildWrapper, nil, children...),
	}
}

func (w WrapperDef) RendersElement() react.Element {
	return w.Render()
}
